import { parseProductEnv } from "@launch/config";

export const productEnv = parseProductEnv({
  EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY:
    process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY,
  EXPO_PUBLIC_CONVEX_URL: process.env.EXPO_PUBLIC_CONVEX_URL,
  EXPO_PUBLIC_POSTHOG_KEY: process.env.EXPO_PUBLIC_POSTHOG_KEY,
  EXPO_PUBLIC_SENTRY_DSN: process.env.EXPO_PUBLIC_SENTRY_DSN,
  EXPO_PUBLIC_REVENUECAT_APPLE_KEY:
    process.env.EXPO_PUBLIC_REVENUECAT_APPLE_KEY,
  EXPO_PUBLIC_REVENUECAT_GOOGLE_KEY:
    process.env.EXPO_PUBLIC_REVENUECAT_GOOGLE_KEY,
  EXPO_PUBLIC_ENABLE_MOCKS: process.env.EXPO_PUBLIC_ENABLE_MOCKS,
});
